Design change #1
rimmer/My-Horoskope pull request #65
Opened 2021-02-21 12:38 UTC by bgoncharuck

- Design was redone, close #63, close #64, new icon.
- Calendar and some buttons clicks check
- Also, userpoll was fixed again, now finally.
But we need to look if any generated files will have conflicts in future updates (g.dart)
- Some structure changes, because our daily screen is really huge.
- Shadows and some other design changes
- Localization to other languages can take a quite time, especially prediction translations.

In-progress:
Some sort of notation placed above calendar and any other changes discussed today

2021-02-23 17:02 UTC, bgoncharuck commented on packages/mobile_app/lib/components/accent_blackboard.dart
> +  // @override
Forget to remove these ones

2021-02-25 23:08 UTC, rimmer requested changes

2021-02-25 23:08 UTC, rimmer commented on packages/data/abstract/predictions/lib/src/get_element_algo/date_time.dart
> +      throw ("Predictions was not loaded or not correct.");
```suggestion
      throw ("Predictions were not loaded or not correct.");
```

2021-02-25 23:08 UTC, rimmer commented on packages/language/lib/language.dart
> +  static String yourPropheciesNotation = locale.yourPropheciesNotation;
*Notation* sounds bit blurry. I would suggest *Hint* for example: `yourPropheciesHint`. This is relevant to all of such below

2021-02-25 23:08 UTC, rimmer commented on packages/mobile_app/lib/components/accent_blackboard.dart
> +  // }
Do we need those?

2021-02-25 23:08 UTC, rimmer commented on packages/mobile_app/lib/components/notation.dart
> +          borderRadius: BorderRadius.circular(8.0)),
Formatting?

2021-02-25 23:08 UTC, rimmer commented on packages/mobile_app/lib/components/prophecy_sheet_divider.dart
> +      width: double.infinity,
Not a blocker, but this is a sign of possible problems in future :)

2021-02-25 23:08 UTC, rimmer commented on packages/mobile_app/lib/components/title_description.dart
> +            fontWeight: FontWeight.w700,
I would suggest to extract set of text styles and reuse them. It will also bring some unity in design

2021-02-25 23:08 UTC, rimmer commented on packages/mobile_app/lib/components/title_description.dart
> +          child: SvgPicture.asset("assets/widget/title_info.svg"),
Does it mean that after every state change `SvgPicture` reopens `title_info.svg` and reads it from scratch? It very likely from what I see

2021-02-25 23:08 UTC, rimmer commented on packages/mobile_app/lib/components/yesterday_poll.dart
> +              height: 34.0,
This hardcoding made one kitten die 🐱

2021-02-25 23:08 UTC, rimmer commented on packages/mobile_app/lib/main.dart
> +class AsyncActions extends StatefulWidget {
What this class does? Not clear from the naming (or perhaps add a dart doc comment?)

2021-02-25 23:08 UTC, rimmer commented on packages/mobile_app/lib/screens/daily/screen/screen.dart
> +            notAvaibleButton(),
```suggestion
            notAvailableButton(),
```

2021-02-25 23:08 UTC, rimmer commented on packages/data/platform/status_file_flutter/lib/src/status_file.dart
> +class StatusFile {
I would rather save this one setting to a user profile

2021-02-25 23:08 UTC, rimmer commented on packages/blocs/user_poll/pubspec.yaml
> +publish_to: none
Thanks for adding this everywhere, less warnings

2021-02-27 08:18 UTC, bgoncharuck commented on packages/mobile_app/lib/components/notation.dart
> +          borderRadius: BorderRadius.circular(8.0)),
![image](https://user-images.githubusercontent.com/25586948/109381793-0c0db180-78e5-11eb-92a8-a5e68e8ead8e.png)
This one thing

2021-02-27 08:30 UTC, bgoncharuck commented on packages/mobile_app/lib/components/prophecy_sheet_divider.dart
> +      width: double.infinity,
It is that thing, 
![image](https://user-images.githubusercontent.com/25586948/109382072-cfdb5080-78e6-11eb-9d1a-32dd55e1a5c3.png)

And double.infinity is widely used

2021-02-27 08:38 UTC, bgoncharuck commented on packages/mobile_app/lib/components/title_description.dart
> +          child: SvgPicture.asset("assets/widget/title_info.svg"),
It provides wrappers for getting assets from multiple sources and caching the resultant Picture. 
It does not render the data to an Image at any point.
https://pub.dev/packages/flutter_svg

Even though, if parent widget is rebuilt, this thing is not

2021-02-27 11:51 UTC, rimmer commented on packages/mobile_app/lib/components/notation.dart
> +          borderRadius: BorderRadius.circular(8.0)),
I was about indentation.

2021-02-27 11:55 UTC, rimmer commented on packages/data/abstract/predictions/lib/src/get_element_algo/date_time.dart
> +      throw ("Predictions was not loaded or not correct.");
You've marked this as resolved. Any reasons not accepting that? Seem like type

2021-02-27 11:58 UTC, rimmer commented on packages/data/platform/status_file_flutter/lib/src/status_file.dart
> +class StatusFile {
I'm fine with keeping it since the change might take a while

2021-02-27 15:15 UTC, bgoncharuck commented on packages/mobile_app/lib/components/notation.dart
> +          borderRadius: BorderRadius.circular(8.0)),
Oh no, color changed to gradient =)

2021-02-27 19:16 UTC, bgoncharuck commented on packages/data/abstract/predictions/lib/src/get_element_algo/date_time.dart
> +      throw ("Predictions was not loaded or not correct.");
It is resolved in commit

2021-02-28 08:07 UTC, rimmer approved these changes
All good

2021-02-28 11:52 UTC, merged